# Generated by Django 5.1.4 on 2025-01-08 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_answer_rating'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='answer',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='answerdislike',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='answerlike',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='questiondislike',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='questionlike',
            name='updated_at',
        ),
    ]
